# PID of current job: 3621140
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "colu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "F", 25, "none", -1, "mean", 0)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "MedianNorm", "CrNorm", "ParetoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-FC.Anal(mSet, 2.0, 0, FALSE)
mSet<-PlotFC(mSet, "fc_0_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, F, 0.05, FALSE, TRUE, "fdr", FALSE)
mSet<-PlotTT(mSet, "tt_0_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, T, 0.05, FALSE, FALSE, "fdr", FALSE)
mSet<-PlotTT(mSet, "tt_1_", "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 2.0, 0, F, 0.1, TRUE, "raw")
mSet<-PlotVolcano(mSet, "volcano_0_",1, 0, "png", 72, width=NA, 5)
mSet<-Volcano.Anal(mSet, FALSE, 2.0, 0, T, 0.05, FALSE, "raw")
mSet<-PlotVolcano(mSet, "volcano_1_",1, 0, "png", 72, width=NA, 5)
mSet<-PlotStaticCorrHeatMap(mSet, "corr_1_", "png", 72, width=NA, "col", "pearson", "bwm", "overview", T, F, 0.0)
mSet<-PCA.Anal(mSet)
mSet<-PlotPCAPairSummary(mSet, "pca_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPCAScree(mSet, "pca_scree_0_", "png", 72, width=NA, 5)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotPCALoading(mSet, "pca_loading_0_", "png", 72, width=NA, 1,2);
mSet<-PlotPCABiplot(mSet, "pca_biplot_0_", "png", 72, width=NA, 1,2,10)
mSet<-PlotPCA3DLoading(mSet, "pca_loading3d_0_", "json", 1,2,3)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-SPLSR.Anal(mSet, 5, 10, "same", "Mfold", 5, F)
mSet<-PlotSPLSPairSummary(mSet, "spls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotSPLS2DScore(mSet, "spls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0,"na")
mSet<-PlotSPLS3DScoreImg(mSet, "spls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotSPLSLoading(mSet, "spls_loading_0_", "png", 72, width=NA, 1,"overview");
mSet<-PlotSPLS3DLoading(mSet, "spls_loading3d_0_", "json", 1,2,3)
mSet<-SPLSR.Anal(mSet, 5, 10, "same", "Mfold", 5, T)
mSet<-PlotSPLSDA.Classification(mSet, "spls_cv_0_", "png", 72, width=NA)
mSet<-SPLSR.Anal(mSet, 5, 10, "same", "loo", 5, T)
mSet<-PlotSPLSDA.Classification(mSet, "spls_cv_1_", "png", 72, width=NA)
mSet<-OPLSR.Anal(mSet, reg=TRUE)
mSet<-PlotOPLS2DScore(mSet, "opls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotOPLS.Splot(mSet, "opls_splot_0_", "all", "png", 72, width=NA);
mSet<-PlotOPLS.Imp(mSet, "opls_imp_0_", "png", 72, width=NA, "vip", "tscore", 15,FALSE)
mSet<-PlotOPLS.MDL(mSet, "opls_mdl_0_", "png", 72, width=NA)
mSet<-SAM.Anal(mSet, "d.stat", FALSE, TRUE, 0.0, "sam_imp_0_")
mSet<-PlotSAM.Cmpd(mSet, "sam_imp_0_", "png", 72, width=NA)
mSet<-PlotSAM.FDR(mSet, "sam_view_0_", "png", 72, width=NA)
mSet<-EBAM.Init(mSet, FALSE, TRUE, FALSE, -99.0, 0.9, "ebam_view_0_", "ebam_imp_0_")
mSet<-PlotEBAM.Cmpd(mSet, "ebam_imp_0_", "png", 72, width=NA)
mSet<-PlotHCTree(mSet, "tree_0_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-PlotStaticHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8,8, "overview", T, T, NULL, T, F, T, T, T)
mSet<-SOM.Anal(mSet, 1,3,"linear","gaussian")
mSet<-PlotSOM(mSet, "som_0_", "png", 72, width=NA, "default", "F")
mSet<-PlotClustPCA(mSet, "som_pca_0_", "png", 72, width=NA, "default", "som", "F")
mSet<-Kmeans.Anal(mSet, 3)
mSet<-PlotKmeans(mSet, "km_0_", "png", 72, width=NA, "default", "F")
mSet<-PlotClustPCA(mSet, "km_pca_0_", "png", 72, width=NA, "default", "km", "F")
mSet<-RF.Anal(mSet, 500,7,1)
mSet<-PlotRF.Classify(mSet, "rf_cls_0_", "png", 72, width=NA)
mSet<-PlotRF.VIP(mSet, "rf_imp_0_", "png", 72, width=NA)
mSet<-PlotRF.Outlier(mSet, "rf_outlier_0_", "png", 72, width=NA)
mSet<-RF.Anal(mSet, 1000,2,1)
mSet<-PlotRF.Classify(mSet, "rf_cls_1_", "png", 72, width=NA)
mSet<-PlotRF.VIP(mSet, "rf_imp_1_", "png", 72, width=NA)
mSet<-PlotRF.Outlier(mSet, "rf_outlier_1_", "png", 72, width=NA)
mSet<-RF.Anal(mSet, 2000,5,1)
mSet<-PlotRF.Classify(mSet, "rf_cls_2_", "png", 72, width=NA)
mSet<-PlotRF.VIP(mSet, "rf_imp_2_", "png", 72, width=NA)
mSet<-PlotRF.Outlier(mSet, "rf_outlier_2_", "png", 72, width=NA)
mSet<-RSVM.Anal(mSet, 10)
mSet<-PlotRSVM.Classification(mSet, "svm_cls_0_", "png", 72, width=NA)
mSet<-PlotRSVM.Cmpd(mSet, "svm_imp_0_", "png", 72, width=NA)
mSet<-SaveTransformedData(mSet)
