#!/usr/bin/env Rscript
# =============================================================================
# 00_derive_gene_lists.R — regenerate the enrichment input gene lists
# =============================================================================
# The gene lists in data/gene_lists/ are the input to 00_compute_enrichment.R,
# which produces the tables that figures 10-12 display. They were originally
# committed as static files, which meant that changing the significance
# threshold silently left the enrichment figures describing the OLD gene set.
# This script derives them from the MAGeCK gene summaries at the threshold
# currently in force, so the whole chain moves together.
#
# Selection rule (reproduces the committed lists exactly at p < 0.05):
#   a gene is included when min(neg p-value, pos p-value) < SIG_THRESH in the
#   relevant comparison. This is ALWAYS the nominal, uncorrected p-value — the
#   sign-based rule, which retains direction-DISCORDANT genes
#   (APOC1, TECR, TKTL1 at the thesis threshold). This is deliberately the same
#   rule as `sig` in load_gene_summary(), NOT the stricter concordant rule used
#   for figure colouring.
#
#   all_significant_25.txt        union across all three comparisons
#   Rpost_vs_R0_significant_18.txt  Rpost_vs_R0 only
#
# The "25" and "18" in the filenames are historical — they are the counts at the
# thesis threshold. Run with --check to verify without writing.
#
# Usage:
#   Rscript crispr_screen/scripts/00_derive_gene_lists.R          # write
#   Rscript crispr_screen/scripts/00_derive_gene_lists.R --check  # verify only
# =============================================================================

source(here::here("crispr_screen", "R", "utils.R"))

CHECK_ONLY <- "--check" %in% commandArgs(trailingOnly = TRUE)

TARGETS <- list(
  list(file = "all_significant_25.txt",
       comparisons = names(COMPARISONS),
       label = "union across all three comparisons"),
  list(file = "Rpost_vs_R0_significant_18.txt",
       comparisons = "Rpost_vs_R0",
       label = "Rpost_vs_R0 only")
)

# Membership is ALWAYS defined on the nominal (uncorrected) p-value, whatever
# SIG_METRIC is set to. Which genes were submitted to enrichment is a property of
# the screen's hit-calling; the FDR mode changes how enrichment TERMS are
# filtered for display, not which genes went in. Reading `pval_raw` rather than
# the mode-dependent `pval` keeps run_crispr_analysis_fdr05.R working on the
# thesis gene sets, which is its documented purpose.
significant_genes <- function(comparisons) {
  hits <- unlist(lapply(comparisons, function(cn) {
    d <- load_gene_summary(cn, SIG_THRESH)
    d$id[d$pval_raw < SIG_THRESH]
  }))
  sort(unique(hits))
}

read_committed <- function(path) {
  if (!file.exists(path)) return(character())
  g <- trimws(readLines(path, warn = FALSE))
  sort(g[nzchar(g)])
}

status <- 0L
for (t in TARGETS) {
  path    <- file.path(GENE_DIR, t$file)
  derived <- significant_genes(t$comparisons)
  onDisk  <- read_committed(path)
  same    <- identical(derived, onDisk)

  # Always reported as "p" — membership never uses the FDR, even in FDR mode.
  message(sprintf("%-32s p < %.3g -> %d genes (on disk: %d) %s",
                  t$file, SIG_THRESH, length(derived),
                  length(onDisk), if (same) "[match]" else "[DIFFERS]"))

  if (!same) {
    added   <- setdiff(derived, onDisk)
    removed <- setdiff(onDisk, derived)
    if (length(added))   message("    + ", paste(added, collapse = ", "))
    if (length(removed)) message("    - ", paste(removed, collapse = ", "))
    if (CHECK_ONLY) status <- 1L
  }

  if (!CHECK_ONLY) {
    dir.create(GENE_DIR, showWarnings = FALSE, recursive = TRUE)
    writeLines(derived, path)
  }
}

if (!CHECK_ONLY) {
  writeLines(c(
    "# gene_lists provenance — generated by 00_derive_gene_lists.R",
    "",
    paste0("criterion  : nominal p-value < ", SIG_THRESH),
    paste0("rule       : min(neg p-value, pos p-value) < threshold (sign-based)"),
    paste0("source     : MAGeCK gene summaries in crispr_screen/data/"),
    paste0("generated  : ", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
    "",
    "Do not edit these lists by hand — rerun the script instead.",
    "Verify at any time with:  Rscript crispr_screen/scripts/00_derive_gene_lists.R --check"
  ), file.path(GENE_DIR, "PROVENANCE.txt"))
  message("Gene lists and PROVENANCE.txt written to ", GENE_DIR)
} else if (status != 0L) {
  message("\nGene lists are STALE for the current threshold.")
  message("Regenerate them, then recompute enrichment:")
  message("  Rscript crispr_screen/scripts/00_derive_gene_lists.R")
  message("  Rscript crispr_screen/scripts/00_compute_enrichment.R")
}

quit(save = "no", status = status)
